// Package cache owns the Redis client used for non-authoritative application
// state such as rate limits, OTPs and short-lived sessions.
package cache

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	redis "github.com/redis/go-redis/v9"

	"github.com/netcore-isp/netcore/internal/config"
)

// Redis is the application's Redis client.
type Redis struct {
	client *redis.Client
	addr   string
}

var (
	ErrRateLimitUnavailable = errors.New("redis: rate limit unavailable")
	ErrOTPUnavailable       = errors.New("redis: OTP challenge unavailable")
)

// AllowSlidingWindow atomically enforces a sliding-window limit. Keys are
// supplied by callers as non-PII digests; Redis should not become a second
// database of raw e-mail addresses, phone numbers or IP addresses.
//
// Auth endpoints treat ErrRateLimitUnavailable as fail-closed. Other endpoint
// classes can apply their documented degradation policy at their boundary.
func (r *Redis) AllowSlidingWindow(ctx context.Context, key string, limit int64, window time.Duration) (bool, error) {
	if r == nil || r.client == nil || r.addr == "" {
		return false, ErrRateLimitUnavailable
	}
	if key == "" || limit < 1 || window <= 0 {
		return false, fmt.Errorf("redis: invalid rate-limit arguments")
	}

	member, err := randomMember()
	if err != nil {
		return false, err
	}
	windowMS := window.Milliseconds()
	if windowMS < 1 {
		return false, fmt.Errorf("redis: rate-limit window must be at least 1ms")
	}

	result, err := slidingWindowScript.Run(ctx, r.client, []string{key}, windowMS, limit, member).Int64()
	if err != nil {
		return false, fmt.Errorf("%w: %v", ErrRateLimitUnavailable, err)
	}
	return result == 1, nil
}

var slidingWindowScript = redis.NewScript(`
local now = redis.call('TIME')
local now_ms = now[1] * 1000 + math.floor(now[2] / 1000)
local start_ms = now_ms - tonumber(ARGV[1])
redis.call('ZREMRANGEBYSCORE', KEYS[1], '-inf', start_ms)
local count = redis.call('ZCARD', KEYS[1])
if count >= tonumber(ARGV[2]) then
  redis.call('PEXPIRE', KEYS[1], tonumber(ARGV[1]))
  return 0
end
redis.call('ZADD', KEYS[1], now_ms, ARGV[3])
redis.call('PEXPIRE', KEYS[1], tonumber(ARGV[1]))
return 1
`)

// CreateOTPChallenge stores a short-lived OTP digest. The challenge ID is
// generated by the authentication service and is opaque to callers; neither a
// destination nor the raw OTP ever enters Redis. A caller may store a
// fixed-length recipient binding digest to make a code action- and recipient-
// specific without retaining personally identifying information.
func (r *Redis) CreateOTPChallenge(ctx context.Context, challengeID, purpose string, binding, digest []byte, ttl time.Duration) error {
	if r == nil || r.client == nil || r.addr == "" {
		return ErrOTPUnavailable
	}
	if challengeID == "" || purpose == "" || (len(binding) != 0 && len(binding) != 32) || len(digest) != 32 || ttl <= 0 || ttl.Milliseconds() < 1 {
		return fmt.Errorf("redis: invalid OTP challenge arguments")
	}
	created, err := createOTPChallengeScript.Run(
		ctx, r.client, []string{otpChallengeKey(challengeID)}, digest, purpose, binding, ttl.Milliseconds(),
	).Int64()
	if err != nil {
		return fmt.Errorf("%w: %v", ErrOTPUnavailable, err)
	}
	if created != 1 {
		return fmt.Errorf("%w: challenge collision", ErrOTPUnavailable)
	}
	return nil
}

// ConsumeOTPChallenge atomically checks an OTP digest, counts every attempt
// and removes the challenge on success or after the final allowed attempt.
// Authentication boundaries must treat an unavailable challenge store as
// fail-closed.
func (r *Redis) ConsumeOTPChallenge(ctx context.Context, challengeID, purpose string, binding, digest []byte, maxAttempts int64) (bool, error) {
	if r == nil || r.client == nil || r.addr == "" {
		return false, ErrOTPUnavailable
	}
	if challengeID == "" || purpose == "" || (len(binding) != 0 && len(binding) != 32) || len(digest) != 32 || maxAttempts < 1 {
		return false, fmt.Errorf("redis: invalid OTP verification arguments")
	}
	matched, err := consumeOTPChallengeScript.Run(
		ctx, r.client, []string{otpChallengeKey(challengeID)}, digest, purpose, binding, maxAttempts,
	).Int64()
	if err != nil {
		return false, fmt.Errorf("%w: %v", ErrOTPUnavailable, err)
	}
	return matched == 1, nil
}

// DeleteOTPChallenge removes a challenge when delivery fails. It is
// best-effort only: its caller still returns the delivery error.
func (r *Redis) DeleteOTPChallenge(ctx context.Context, challengeID string) error {
	if r == nil || r.client == nil || r.addr == "" {
		return ErrOTPUnavailable
	}
	if challengeID == "" {
		return fmt.Errorf("redis: OTP challenge ID is required")
	}
	if err := r.client.Del(ctx, otpChallengeKey(challengeID)).Err(); err != nil {
		return fmt.Errorf("%w: %v", ErrOTPUnavailable, err)
	}
	return nil
}

func otpChallengeKey(challengeID string) string {
	return "netcore:otp:challenge:" + challengeID
}

var createOTPChallengeScript = redis.NewScript(`
if redis.call('EXISTS', KEYS[1]) ~= 0 then
  return 0
end
redis.call('HSET', KEYS[1], 'digest', ARGV[1], 'purpose', ARGV[2], 'binding', ARGV[3], 'attempts', 0)
redis.call('PEXPIRE', KEYS[1], tonumber(ARGV[4]))
return 1
`)

var consumeOTPChallengeScript = redis.NewScript(`
if redis.call('EXISTS', KEYS[1]) == 0 then
  return 0
end
local attempts = redis.call('HINCRBY', KEYS[1], 'attempts', 1)
if attempts > tonumber(ARGV[4]) then
  redis.call('DEL', KEYS[1])
  return 0
end
if redis.call('HGET', KEYS[1], 'purpose') == ARGV[2] and redis.call('HGET', KEYS[1], 'binding') == ARGV[3] and redis.call('HGET', KEYS[1], 'digest') == ARGV[1] then
  redis.call('DEL', KEYS[1])
  return 1
end
if attempts >= tonumber(ARGV[4]) then
  redis.call('DEL', KEYS[1])
end
return 0
`)

func randomMember() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("redis: generate rate-limit member: %w", err)
	}
	return hex.EncodeToString(b[:]), nil
}

// New constructs a client without contacting Redis. Redis is deliberately not
// a startup-critical dependency: an outage must degrade the affected features,
// not stop every API instance from serving traffic.
func New(cfg config.Redis) *Redis {
	return &Redis{
		addr: cfg.Addr,
		client: redis.NewClient(&redis.Options{
			Addr:         cfg.Addr,
			Password:     cfg.Password,
			DialTimeout:  cfg.Timeout,
			ReadTimeout:  cfg.Timeout,
			WriteTimeout: cfg.Timeout,
			PoolTimeout:  cfg.Timeout,
		}),
	}
}

// Ping checks Redis connectivity. It is used as a non-critical health check.
func (r *Redis) Ping(ctx context.Context) error {
	if r == nil || r.client == nil {
		return errors.New("redis: client is not initialized")
	}
	if r.addr == "" {
		return errors.New("redis: address is not configured")
	}
	return r.client.Ping(ctx).Err()
}

// Close releases client resources.
func (r *Redis) Close() error {
	if r == nil || r.client == nil {
		return nil
	}
	return r.client.Close()
}
